name: edubridge_app
description: EduBridge — تطبيق تعليمي لأطفال ذوي الاحتياجات الخاصة
publish_to: 'none'
version: 1.4.0+6

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.0
  flutter_tts: ^4.2.0   # قراءة محتوى الدروس صوتياً (accessibility)
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # أصول التطبيق (شعار جسر)
  assets:
    - assets/icon.png
